name: {{cookiecutter.name}}
version: {{cookiecutter.version}}

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >=4.9 && <5

library:
  source-dirs:        src

executables:
  {{cookiecutter.name}}:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{cookiecutter.name}}

tests:
  tests:
    main: {{cookiecutter.module}}Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{cookiecutter.name}}
      - HUnit

benchmarks:
  {{cookiecutter.name}}-bench:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{cookiecutter.name}}
      - criterion